@extends('common.base-template-internal')
@section('content')

<div class="container-flex internal">

    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis, vel iusto earum expedita enim delectus et voluptatibus, dicta ut incidunt hic minus doloremque ratione excepturi assumenda temporibus consectetur commodi locale_accept_from_http Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugit possimus labore, ullam hic inventore non laudantium voluptatibus consequatur necessitatibus vitae assumenda similique, ea exercitationem ex explicabo adipisci unde ipsum enim!</placeat></p>
    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis, vel iusto earum expedita enim delectus et voluptatibus, dicta ut incidunt hic minus doloremque ratione excepturi assumenda temporibus consectetur commodi locale_accept_from_http Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugit possimus labore, ullam hic inventore non laudantium voluptatibus consequatur necessitatibus vitae assumenda similique, ea exercitationem ex explicabo adipisci unde ipsum enim!</placeat></p>
    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis, vel iusto earum expedita enim delectus et voluptatibus, dicta ut incidunt hic minus doloremque ratione excepturi assumenda temporibus consectetur commodi locale_accept_from_http Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugit possimus labore, ullam hic inventore non laudantium voluptatibus consequatur necessitatibus vitae assumenda similique, ea exercitationem ex explicabo adipisci unde ipsum enim!</placeat></p>
    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis, vel iusto earum expedita enim delectus et voluptatibus, dicta ut incidunt hic minus doloremque ratione excepturi assumenda temporibus consectetur commodi locale_accept_from_http Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugit possimus labore, ullam hic inventore non laudantium voluptatibus consequatur necessitatibus vitae assumenda similique, ea exercitationem ex explicabo adipisci unde ipsum enim!</placeat></p>
    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis, vel iusto earum expedita enim delectus et voluptatibus, dicta ut incidunt hic minus doloremque ratione excepturi assumenda temporibus consectetur commodi locale_accept_from_http Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugit possimus labore, ullam hic inventore non laudantium voluptatibus consequatur necessitatibus vitae assumenda similique, ea exercitationem ex explicabo adipisci unde ipsum enim!</placeat></p>
    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis, vel iusto earum expedita enim delectus et voluptatibus, dicta ut incidunt hic minus doloremque ratione excepturi assumenda temporibus consectetur commodi locale_accept_from_http Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugit possimus labore, ullam hic inventore non laudantium voluptatibus consequatur necessitatibus vitae assumenda similique, ea exercitationem ex explicabo adipisci unde ipsum enim!</placeat></p>
    <p class = "pb-5" >Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis, vel iusto earum expedita enim delectus et voluptatibus, dicta ut incidunt hic minus doloremque ratione excepturi assumenda temporibus consectetur commodi locale_accept_from_http Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugit possimus labore, ullam hic inventore non laudantium voluptatibus consequatur necessitatibus vitae assumenda similique, ea exercitationem ex explicabo adipisci unde ipsum enim!</placeat></p>

</div>